my_anime_pipeline:
  outputs:
    dev:
      type: postgres
      host: db
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('DB_NAME') }}"
      schema: public
      threads: 1
  target: dev